### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by amercader** [keitaroinc/ckanext-saml2auth#13]
This extension is great and a big improvement from previous versions of ckanext-saml2. One thing I would like to know more about is your plans regarding extensibility for it.

By extensibility I mean supporting custom business logic around the SAML2 authentication for specific projects. Here are some examples (all real from projects I've worked on):

* Custom SAML config. [pysaml](https://pysaml2.readthedocs.io/en/latest/howto/config.html) has lots of configuration options and sometimes you need to tweak some of them, and it would be nice to not have to add CKAN config options to cover all cases
* Adding custom fields (plugin extras) to created/updated users based on SAML2 claims
* Adding users to organizations with different roles based on SAML2 claims
* Prevent users from editing their details in CKAN

One of the problems with the old extension is that it included code to deal with several features like these that were sepcific to one or a small number of projects, and many times involving layers of code not directly related with authentication (actions, authorization, etc). This all made the code base unnecessarily complex. I think the approach of keeping this plugin lean and focus on the core functionality is the right one.

At the same time, it's good that other plugins can extend the functionality to support custom logic. Traditionally this has been done in CKAN using interfaces that plugins can implement. Here's a quick stub of how this interface could look like:

```python
class ISaml2Auth(Interface):

    def sp_config(self, sp_config):
        """"
        Gets the config object generated by get_config() allowing plugins to tweak it
        """
        pass

    def before_user_update(self, user_dict, saml_claims):
        """
        Gets the user data dict before updating a user alongside all the claims
        contained in the SAML2 token (currently in auth_response.ava)
        """
        pass

    def before_user_create(self, user_dict, saml_claims):
        """
        Gets the user data dict before creating a user alongside all the claims
        contained in the SAML2 token
        """
        pass

    def after_login(self, resp, saml_claims):
        """
        Called once the user has been logged in, just before returning the request, and passing
        the request object, so plugins can issue redirects if needed. At this point they can use
        g.user to get the logged in user
        """
        pass
```

As I said I didn't put much thought into the actual methods and params passed but hopefully they give an idea of what I'm suggesting. Of course I'm also open to other approaches if you think there are better ones.

Let me know your thoughts. I'd be happy to contribute support for the interface if this sounds like a good way forward.

**Comment by mbocevski** [comment]
@amercader you're spot on! Our design approach was to keep the plugin lean and easy to use in order to provide easy of use in getting SAML capabilities to CKAN.

We have been thinking of going with a similar approach as you are suggesting, we haven't put any work into it yet, so if you want to contribute to the design of the interface it would be awesome!

Some challenges that I see are:
> Custom SAML config

I agree we should not add CKAN options, but rather provide a good interface for users to be able to modify this. I like the idea of exposing this in the interface, however, I'm also open to ideas on whether we can also build something in the plugin itself that will be easy to use for those that have a need of utilizing different options. The latter when we were thinking about it, I think the best option is to have an override for the whole `sp_config`.
>Adding users to organizations with different roles based on SAML2 claims

As you might have seen we have not included anything about organization/groups logic or mapping from SAML claims. The reasoning behind that is that majority of users don't use that and leave it to those who know what flows they want to be able to implement through an interface. If you have any ideas of anything in the core that can make this easier without adding too much complexity please suggest, we are open to ideas.

>CKAN 2.8/2.7

I think we should only have the interface on `main` and not backport it to CKAN 2.8/2.7, the reasoning is that we can definitely leverage things like `plugin_extras` etc that are available in 2.9+. So I would suggest we keep the interface only for 2.9+ and design it with 2.9+ in mind. Afterwards if someone in the community really needs it in 2.8 they can backport it.

**Comment by amercader** [comment]
> We have been thinking of going with a similar approach as you are suggesting, we haven't put any work into it yet, so if you want to contribute to the design of the interface it would be awesome!

OK, once we start on actual migration work I'll work on the interface in parallel

> The latter when we were thinking about it, I think the best option is to have an override for the whole sp_config.

How would that work, extensions would register an entrypoint for their own sp_config function / module? It doesn't look like much easier that implementing an interface method but maybe I'm not understanding it right. Or maybe you mean that people can provide a JSON file or something with the configuration?

> 

>> Adding users to organizations with different roles based on SAML2 claims

> If you have any ideas of anything in the core that can make this easier without adding too much complexity please suggest, we are open to ideas
I think that hooks like the ones I suggested would allow advanced users to call whatever organization / member actions they need *in their own plugins* without adding complexity to saml2auth

> CKAN 2.8/2.7

Sounds good to me.

**Comment by mbocevski** [comment]
>OK, once we start on actual migration work I'll work on the interface in parallel

Great, feel free to push a draft PR once you have something, so we can collaborate on that.

>Or maybe you mean that people can provide a JSON file or something with the configuration?

Yes, cause by having it as a configuration like for instance a JSON file, then you can modify the configuration without the need to 
update any code in the extension. This is useful because any changes on the SAML backend would be easier to handle. My reasoning is because most of `sp_config` is configuration options. If a better option is to have an interface we can obviously go down that route.

>I think that hooks like the ones I suggested would allow advanced users to call whatever organization / member actions they 
need in their own plugins without adding complexity to saml2auth

Also mapping of attributes and etc would be handled in their own plugins? I think that sounds good.

**Comment by adborden** [comment]
I think one more hook that would be helpful is `before_identify`. Maybe this can be done with the existing IAuthentication.identify (I don't recall if multiple plugins can hook into that, or maybe there is a quirk to doing it).

In the case of Data.gov which uses Login.gov, the SAML provider is not specific to an organization. Anyone in the world can create an account and login. Having a hook like `before_identify` could be used to reject logins for users who might have a valid account with the SAML Idp but we don't want to create an account within CKAN, and reject their login. In Data.gov case, this is really a user-by-user case. It's not like a SAML attribute that we would key off of, we really are looking for per-user control.
